# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171116_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belongings',
            name='buildings',
        ),
        migrations.RemoveField(
            model_name='belongings',
            name='items',
        ),
        migrations.RemoveField(
            model_name='belongings',
            name='units',
        ),
        migrations.AddField(
            model_name='belongings',
            name='army',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belongings',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belongings',
            name='market',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belongings',
            name='warrior1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belongings',
            name='warrior2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='belongings',
            name='warrior3',
            field=models.IntegerField(default=0),
        ),
    ]
