# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171116_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongings',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
