# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_belongings_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
