# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='population',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
