# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171122_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='population',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
