# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171126_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tribe',
            field=models.IntegerField(choices=[('1', 'tribeA'), ('2', 'tribeB')], default=1),
        ),
    ]
