# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20171128_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belongings',
            name='acedemy',
        ),
        migrations.AddField(
            model_name='belongings',
            name='academy',
            field=models.IntegerField(default=0),
        ),
    ]
