# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
            ],
        ),
    ]
