# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='defaultname', max_length=100),
            preserve_default=False,
        ),
    ]
