# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='time_to_make',
            field=models.IntegerField(default=10),
        ),
    ]
