# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_buildinginprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinginprogress',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
