# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_buildinginprogress_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinginprogress',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
