# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='population',
            field=models.IntegerField(default=1),
        ),
    ]
