# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0011_building_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrior1', models.IntegerField(default=0)),
                ('warrior2', models.IntegerField(default=0)),
                ('warrior3', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('begin', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(blank=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attacks_done', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='defences_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
