# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0014_auto_20171126_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
