# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0015_building_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('finished', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='culture_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='science_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='culture_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='science_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='culture_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='population',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='science_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitinprogress',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.Unit'),
        ),
        migrations.AddField(
            model_name='unitinprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
